### PR TITLE
hide the thumbv* target files

### PR DESCRIPTION
**Pull request by japaric**
due to how Cargo works, the rustc-cfg in build.rs was picking our target
specifications rather than the one the user meant to use. Placing our
target files in any place other than the root of the Cargo project
avoids the issue.

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0827f8c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0827f8c with merge 0827f8c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.271), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/164521572)
Approved by: japaric
Pushing 0827f8c7f131c95ae9747c0639c1b89070f6c94a to master...

**Pull request merged**
