### PR TITLE
put weak mem* symbols behind an opt-in Cargo feature

### LINKED ISSUE #64: Put weak memcpy et al symbols behind an opt-in Cargo feature

### PR DESCRIPTION
**Pull request by japaric**
closes #64
cc #66

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 66bb08b has been approved by `japaric`

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably #67) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b7fa7d3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b7fa7d3 with merge c56a3f8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.248), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/162066535)
Approved by: japaric
Pushing c56a3f8a6ed678e86f8c4aa79571b919bb99d20a to master...

**Pull request merged**
