### PR TITLE
test the thumbv7em-none-eabihf target

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0404438 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0404438 with merge 0404438...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/161883363)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.
- There's another pull request that is currently being tested, blocking this pull request: #69

**Comment by homunkulus** [comment]
:pushpin: Commit 0404438 has been approved by `japaric`

**Comment by japaric** [comment]
hmm, @homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0404438 with merge fc2a502...

**Comment by japaric** [comment]
The test [passed](https://travis-ci.org/japaric/rustc-builtins/builds/161951640) but I think homu was asleep when that ocurred.

Merging manually.

**Pull request merged**
