### PR TITLE
drop the target files

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 213d929 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 213d929 with merge 213d929...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1c90948 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1c90948 with merge 1c90948...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.284), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/165794925)
Approved by: japaric
Pushing 1c9094814d810a2747cad2551355aa24b479a0a2 to master...

**Pull request merged**
