### PR TITLE
homu test

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9d74cf0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9d74cf0 with merge 9d74cf0...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.236), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/159048126)
Approved by: japaric
Pushing 9d74cf08b8165b7ed8dc7d75d9a55958dcaa3d27 to master...

**Pull request merged**
