### PR TITLE
Add pow functions

### PR DESCRIPTION
**Pull request by mattico**
I still want to clean up the commit history, but otherwise I think this is complete. ~~Can you run the tests on it?~~

### CODE REVIEW

**Comment by mattico** [comment]
Squashed everything but will need rebase after #84.

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably 89ebc46) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by mattico** [comment]
Rebased. Should be mergable now.

**Comment by japaric** [comment]
Can't review right now so I'm just going to pass this homu for testing.

@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 6622c49 with merge 6622c49...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.274), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/164699443)
State: approved= try=True

**Comment by japaric** [comment]
LGTM. We should also stop compiling the compiler-rt implementations of these in build.rs. I'm actually surprised this PR didn't generate an error due to duplicate symbols ... perhaps, the related test I added is not working properly.

**Comment by japaric** [comment]
@homunkulus try

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ff7e3ba has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ff7e3ba with merge 8652c66...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.277), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/164818039)
Approved by: japaric
Pushing 8652c66bdcbdaa662fc980988c5ab1766a506c2b to master...

**Pull request merged**
