### PR TITLE
appveyor failure

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
Testing. Homu shouldn't merge this

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1a6eab8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1a6eab8 with merge 1a6eab8...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.234)

**Comment by japaric** [comment]
@homunkulus good bot!

**Pull request closed without merging**
