### PR TITLE
switch to a current nightly

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4df5deb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4df5deb with merge 4df5deb...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/165413734)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 5908bb7 with merge 5908bb7...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.281), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/165417790)
State: approved= try=True

**Comment by japaric** [comment]
@mattico so, this is interesting. We are currently testing the arm-unknown-linux-gnueabi target with the nightly from 2016-09-21 and the all the tests pass. But in this PR, I tested the same arm target but vs today's nightly and it produces the failures you are seeing in #90 (see above, the first travis failure).

Now, the .travis.yml has a comment that says that we are using the older nightly for arm because of rust-lang/rust#36518 which, iirc, is the problem with u32 -> f32 u32 -> f64 being UB because those are intrinsics implemented in compiler-rt. Now, that particular issue supposedly has already been already fixed (rust-lang/rust#36828) but perhaps the fix is not yet in today's nightly.

**Comment by japaric** [comment]
@mattico Some things you could try to fix #90. Avoid doing a integer -> float (e.g. u32 -> f64) conversion. Maybe try directly generating random floating point values. Otherwise, you could try porting floatsidf and floatdidf to Rust so these tests end up using the Rust implementation rathern than compiler-rt's.

**Pull request merged**
