### PR TITLE
Upstream, take 2

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit e05caa1 with merge e05caa1...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/166601045)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit a163ca7 with merge a163ca7...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.291), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/166605815)
State: approved= try=True

**Comment by alexcrichton** [comment]
r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a163ca7 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e441058 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e441058 with merge e441058...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.292), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/166610998)
Approved by: japaric
Pushing e441058be7b8ef4356f1bdd882639696e2525343 to master...

**Pull request merged**
