### PR TITLE
avoid division overflow in idivmod test

### PR DESCRIPTION
**Pull request by japaric**
backport one commit from #67
should fix the errors seen in #68

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bfa92a8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit bfa92a8 with merge bfa92a8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.243), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/161945660)
Approved by: japaric
Pushing bfa92a862bd902129f6b1cf5532f78cede001b40 to master...

**Pull request merged**
