### PR TITLE
switch compiler-rt to rust-lang's fork

### LINKED ISSUE #85: Integrate UB fix in floatsidf and floatsisf
cf. rust-lang/compiler-rt#24

These fixes are not in the llvm-mirror/compiler-rt repo which we are using.

### PR DESCRIPTION
**Pull request by japaric**
this fork has been patched against the UB in floatsidf and floasisf
closes #85

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+
cc @alexcrichton

**Comment by homunkulus** [comment]
:pushpin: Commit 2706d92 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2706d92 with merge 2706d92...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.278), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/164836507)
Approved by: japaric
Pushing 2706d9264ac52afaffd96c0eab5d2058bd09b65b to master...

**Pull request merged**
