### PR TITLE
homu-ify

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e80fca6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e80fca6 with merge e80fca6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.233), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/159031665), [travis](https://travis-ci.org/japaric/rustc-builtins/builds/159031665)
Approved by: japaric
Pushing e80fca6469dec6f71a3764f7d6ea2fb7b0146453 to master...

**Pull request merged**
