### PR TITLE
Fix nm

### PR DESCRIPTION
**Pull request by japaric**
We were actually running `ci/run.sh` without `set -e` and we were ignoring test failures and failed commands :scream_cat:.

This also undoes #48 which introduced test failures in addsf3 and adddf3 for the arm-unknown-linux-gnueabi target. Sorry @mattico!

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3b8dedd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3b8dedd with merge 3b8dedd...

**Comment by mattico** [comment]
@japaric is there a log of these failures somewhere? Does it look like the same sort of issue we were having with the gnueabihf targets?

**Comment by japaric** [comment]
@mattico arm-unknown-linux-gnueabi

```
failures:

---- float::add::tests::_compiler_rt::__adddf3 stdout ----
        thread 'float::add::tests::_compiler_rt::__adddf3' panicked at '[quickcheck] TEST FAILED. Arguments: (0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004387612278450533, -0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000017204245911120083)', /cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.3.1/src/tester.rs:118
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- float::add::tests::_compiler_rt::__addsf3 stdout ----
        thread 'float::add::tests::_compiler_rt::__addsf3' panicked at '[quickcheck] TEST FAILED. Arguments: (0.000000000000000000000000000000000000000654321, 0.000000000000000000000000000000000000005707838)', /cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.3.1/src/tester.rs:118

---- float::add::tests::_gcc_s::__adddf3 stdout ----
        thread 'float::add::tests::_gcc_s::__adddf3' panicked at '[quickcheck] TEST FAILED. Arguments: (0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000583564295892806, 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000185772095460437)', /cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.3.1/src/tester.rs:118

---- float::add::tests::_gcc_s::__addsf3 stdout ----
        thread 'float::add::tests::_gcc_s::__addsf3' panicked at '[quickcheck] TEST FAILED. Arguments: (0.000000000000000000000000000000000000006809104, 0.000000000000000000000000000000000000004278016)', /cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.3.1/src/tester.rs:118


failures:
    float::add::tests::_compiler_rt::__adddf3
    float::add::tests::_compiler_rt::__addsf3
    float::add::tests::_gcc_s::__adddf3
    float::add::tests::_gcc_s::__addsf3

test result: FAILED. 40 passed; 4 failed; 0 ignored; 0 measured
```

I don't know if the other arm targets were also failing.

> Does it look like the same sort of issue we were having with the gnueabihf targets?

I'm not sure but the same intrinsics are failing, right? addsf3 and adddf3.

**Comment by japaric** [comment]
Ah, but both the vs compiler_rt and vs gcc_s are failing so it's different. On gnueabihf only vs gcc_s was failing iirc.

**Comment by japaric** [comment]
Ah, mips-gnu and mipsel-gnu were also failing :scream_cat:.

**Comment by mattico** [comment]
So there's probably a real issue somewhere. Not looking forward to debugging that...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/164189752)

**Comment by mattico** [comment]
It might be a good idea to remove the add impl for now since it's still broken but the old tests didn't catch it. It might randomly fail if the U{32,64} quickcheck randomly generates a small denormal.

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit d8fa45a with merge d8fa45a...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d0a57cb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d0a57cb with merge d0a57cb...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 89ebc46 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 89ebc46 with merge 89ebc46...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.269), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/164198810)
Approved by: japaric
Pushing 89ebc46f37f58b41dd526b353b34cc270ec2d8e0 to master...

**Pull request merged**
