### PR TITLE
fix duplicate symbol test

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8a32bd3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8a32bd3 with merge 8a32bd3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.276), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/164814654)
Approved by: japaric
Pushing 8a32bd3424a93059fc7e68a3249e77860125fa8c to master...

**Pull request merged**
