### PR TITLE
add missing aeabi aliases

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3c9283a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3c9283a with merge 9e4875c...

**Comment by japaric** [comment]
The test failed on [osx](https://travis-ci.org/japaric/rustc-builtins/jobs/161980347) due to some Travis weirdness. It seems homu got stuck ...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d34be6a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d34be6a with merge d5e38be...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.247), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/162056449)
Approved by: japaric
Pushing d5e38beef9cd27f75a7c7b670ead7e8184c7b93c to master...

**Pull request merged**
