### PR TITLE
test for homu

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8359013 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8359013 with merge 8359013...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.235), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/159043632), [travis](https://travis-ci.org/japaric/rustc-builtins/builds/159043632)
Approved by: japaric
Pushing 8359013890532a8a632ebaa788c91c7ebd4d8e36 to master...

**Pull request merged**
