### PR TITLE
run the full test suite on osx

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 1f257a6 with merge 1f257a6...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/165422880)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit c5e75fd with merge c5e75fd...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/165875461)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit eaa8a17 with merge eaa8a17...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.287), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/165911640)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 24c2a15 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 24c2a15 with merge 24c2a15...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.288), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/165919304)
Approved by: japaric
Pushing 24c2a15f3d868b348b6e78cbd52f8f40d7ff7f73 to master...

**Pull request merged**
