### PR TITLE
appveyor: stop gisting the disassembly

### PR DESCRIPTION
**Pull request by japaric**
it's flaky in its current form and Travis is not producing gist either.

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 69e93de has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 69e93de with merge 69e93de...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/rustc-builtins/build/1.0.256), [status-travis](https://travis-ci.org/japaric/rustc-builtins/builds/163687370)
Approved by: japaric
Pushing 69e93de9d9abd9ba1f59be1e921ee4bb95eb33fb to master...

**Comment by mattico** [comment]
RIP 😢

**Pull request merged**
